pub mod map_name {
    use std::{collections::HashMap, sync::Mutex};
    use once_cell::sync::Lazy;

    #[derive(PartialEq, Eq, Hash, Clone, Copy, PartialOrd, Ord)]
    pub enum MapName {
        AcademyOfRayaLucaria,
        AinselRiver,
        AinselRiverMain,
        AltusPlateau,
        BellumHighway,
        Caelid,
        CapitalOutskirts,
        ConsecratedSnowfield,
        CrumblingFarumAzula,
        DeeprootDepths,
        ElphaelBraceOfTheHaligtree,
        FlamePeak,
        ForbiddenLands,
        GreyollsDragonbarrow,
        LakeOfRot,
        LeyndellAshenCapital,
        LeyndellRoyalCapital,
        Limgrave,
        LiurniaOfTheLakes,
        MiquellasHaligtree,
        MohgwynPalace,
        MoonlightAltar,
        MountaintopsOfTheGiants,
        MtGelmir,
        NokronEternalCity,
        RealmOfShadowBelurat,
        RealmOfShadowEnirIlim,
        RealmOfShadowShadowKeep,
        RealmOfShadowStorehouse,
        RealmOfShadowStoneCoffinFissure,
        RealmOfShadowMidrasManse,
        RealmOfShadowGravesitePlain,
        RealmOfShadowCharosGrave,
        RealmOfShadowCastleEnsis,
        RealmOfShadowCeruleanCoast,
        RealmOfShadowAbyssalWoods,
        RealmOfShadowJaggedPeak,
        RealmOfShadowRauh,
        RealmOfShadowScaduAltus,
        RealmOfShadowScaduview,
        RoundtableHold,
        RuinStrewnPrecipice,
        SiofraRiver,
        StonePlatform,
        Stormhill,
        StormveilCastle,
        StrandedGraveyard,
        SubterraneanShunningGrounds,
        SwampOfAeonia,
        VolcanoManor,
        WeepingPeninsula,
    }

    pub static MAP_NAME: Lazy<Mutex<HashMap<MapName, &str>>> = Lazy::new(|| {
        Mutex::new(HashMap::from([
            (MapName::RoundtableHold, "Table of Lost Grace / Roundtable Hold"),
            (MapName::Limgrave, "Limgrave"),
            (MapName::StrandedGraveyard, "Stranded Graveyard"),
            (MapName::Stormhill, "Stormhill"),
            (MapName::WeepingPeninsula, "Weeping Peninsula"),
            (MapName::StormveilCastle, "Stormveil Castle"),
            (MapName::LiurniaOfTheLakes, "Liurnia of the Lakes"),
            (MapName::BellumHighway, "Bellum Highway"),
            (MapName::RuinStrewnPrecipice, "Ruin-Strewn Precipice"),
            (MapName::MoonlightAltar, "Moonlight Altar"),
            (MapName::AcademyOfRayaLucaria, "Academy of Raya Lucaria"),
            (MapName::AltusPlateau, "Altus Plateau"),
            (MapName::MtGelmir, "Mt. Gelmir"),
            (MapName::CapitalOutskirts, "Capital Outskirts"),
            (MapName::VolcanoManor, "Volcano Manor"),
            (MapName::LeyndellRoyalCapital, "Leyndell, Royal Capital"),
            (MapName::SubterraneanShunningGrounds, "Subterranean Shunning-Grounds"),
            (MapName::LeyndellAshenCapital, "Leyndell, Ashen Capital"),
            (MapName::StonePlatform, "Stone Platform"),
            (MapName::Caelid, "Caelid"),
            (MapName::SwampOfAeonia, "Swamp of Aeonia"),
            (MapName::GreyollsDragonbarrow, "Greyoll's Dragonbarrow"),
            (MapName::ForbiddenLands, "Forbidden Lands"),
            (MapName::MountaintopsOfTheGiants, "Mountaintops of the Giants"),
            (MapName::FlamePeak, "Flame Peak"),
            (MapName::ConsecratedSnowfield, "Consecrated Snowfield"),
            (MapName::MiquellasHaligtree, "Miquella's Haligtree"),
            (MapName::ElphaelBraceOfTheHaligtree, "Elphael, Brace of the Haligtree"),
            (MapName::AinselRiver, "Ainsel River"),
            (MapName::AinselRiverMain, "Ainsel River Main"),
            (MapName::LakeOfRot, "Lake of Rot"),
            (MapName::NokronEternalCity, "Nokron, Eternal City"),
            (MapName::MohgwynPalace, "Mohgwyn Palace"),
            (MapName::SiofraRiver, "Siofra River"),
            (MapName::DeeprootDepths, "Deeproot Depths"),
            (MapName::CrumblingFarumAzula, "Crumbling Farum Azula"),
            (MapName::RealmOfShadowBelurat, "Realm of Shadow - Belurat"),
            (MapName::RealmOfShadowEnirIlim, "Realm of Shadow - Enir-Ilim"),
            (MapName::RealmOfShadowShadowKeep, "Realm of Shadow - Shadow Keep"),
            (MapName::RealmOfShadowStorehouse, "Realm of Shadow - Storehouse"),
            (MapName::RealmOfShadowStoneCoffinFissure, "Realm of Shadow - Stone Coffin Fissure"),
            (MapName::RealmOfShadowMidrasManse, "Realm of Shadow - Midra's Manse"),
            (MapName::RealmOfShadowGravesitePlain, "Realm of Shadow - Gravesite Plain"),
            (MapName::RealmOfShadowCharosGrave, "Realm of Shadow - Charo's Hidden Grave"),
            (MapName::RealmOfShadowCastleEnsis, "Realm of Shadow - Castle Ensis"),
            (MapName::RealmOfShadowCeruleanCoast, "Realm of Shadow - Cerulean Coast"),
            (MapName::RealmOfShadowAbyssalWoods, "Realm of Shadow - Abyssal Woods"),
            (MapName::RealmOfShadowJaggedPeak, "Realm of Shadow - Jagged Peak"),
            (MapName::RealmOfShadowRauh, "Realm of Shadow - Ancient Ruins of Rauh"),
            (MapName::RealmOfShadowScaduAltus, "Realm of Shadow - Scadu Altus"),
            (MapName::RealmOfShadowScaduview, "Realm of Shadow - Scaduview"),
        ]))
    });
}